[package]
name = "axelw/alchemists"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
janitor = "howmanysmall/janitor@^1.15.6"
boattween ="boatbomber/boattween@1.0.1"
inpututil = "sleitnick/input@2.3.0"
tableutil = "sleitnick/table-util@1.2.1"
red = "red-blox/red@2.3.0"
guard = "red-blox/guard@^1.0.0"
loader = "sleitnick/loader@2.0.0"
shake = "sleitnick/shake@1.1.0"
zoneplus = "mattschrubb/zoneplus@3.2.0"