[package]
name = "axelw/spellcasters"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@^1.15.6"
Rewire = "sayhisam1/rewire@0.3.0"
Roact = "roblox/roact@1.4.0"